// Word lists for random miniature name generation
const ADJECTIVES = [
  'Iron',
  'Mystic',
  'Ancient',
  'Crimson',
  'Shadow',
  'Golden',
  'Frozen',
  'Storm',
  'Silver',
  'Dark',
  'Light',
  'Crystal',
  'Burning',
  'Eternal',
  'Phantom',
  'Royal',
  'Savage',
  'Silent',
  'Thunder',
  'Venom',
  'Wild',
  'Arcane',
  'Blessed',
  'Cursed',
  'Dread',
  'Emerald',
  'Fierce',
  'Ghost',
  'Hollow',
  'Immortal',
  'Jade',
  'Keen',
  'Lunar',
  'Molten',
  'Noble',
  'Obsidian',
  'Primal',
  'Radiant',
  'Solar',
  'Twilight',
  'Umbral',
  'Vicious',
  'Wicked',
  'Zealous',
  'Blighted',
  'Celestial',
  'Doomed',
  'Ethereal',
  'Fell',
  'Grim',
] as const;

const NOUNS = [
  'Guardian',
  'Wolf',
  'Knight',
  'Drake',
  'Spirit',
  'Titan',
  'Seeker',
  'Blade',
  'Warrior',
  'Mage',
  'Ranger',
  'Paladin',
  'Rogue',
  'Cleric',
  'Bard',
  'Monk',
  'Sorcerer',
  'Warlock',
  'Druid',
  'Barbarian',
  'Fighter',
  'Wizard',
  'Assassin',
  'Champion',
  'Defender',
  'Enchanter',
  'Hunter',
  'Invoker',
  'Juggernaut',
  'Keeper',
  'Lord',
  'Master',
  'Nomad',
  'Oracle',
  'Protector',
  'Reaper',
  'Sentinel',
  'Slayer',
  'Templar',
  'Vanguard',
  'Warden',
  'Berserker',
  'Crusader',
  'Dervish',
  'Exile',
  'Fury',
  'Gladiator',
  'Herald',
  'Inquisitor',
  'Justiciar',
] as const;

/**
 * Generates a random two-word name for a miniature
 * Format: "Adjective Noun" (e.g., "Iron Guardian", "Mystic Wolf")
 */
export function generateMiniName(): string {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  return `${adjective} ${noun}`;
}
